name: com.ci.flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  get_it: ^4.0.1
  flutter_config: ^1.0.5
  dio: ^3.0.9
  firebase_core: 0.4.4
  cloud_firestore: 0.13.4
  firebase_messaging: ^6.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test: ^1.3.0
  bloc_test: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/strings/
