name: Unit test
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_app:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - name: Lint Code Base
        uses: github/super-linter:latest
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: flutter test --coverage

      - name: Coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage_ci
          path: ./coverage/
